// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/plugins/orbitalimager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbitalImagerPlugin_RequestImagery_FullMethodName   = "/orbitalimager.OrbitalImagerPlugin/RequestImagery"
	OrbitalImagerPlugin_ListImages_FullMethodName       = "/orbitalimager.OrbitalImagerPlugin/ListImages"
	OrbitalImagerPlugin_GetImageMetadata_FullMethodName = "/orbitalimager.OrbitalImagerPlugin/GetImageMetadata"
	OrbitalImagerPlugin_GetImagePacket_FullMethodName   = "/orbitalimager.OrbitalImagerPlugin/GetImagePacket"
)

// OrbitalImagerPluginClient is the client API for OrbitalImagerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrbitalImagerPlugin is Phare's Orbitport Application Plugin.
//
// v0.0.1 surface: a single unary RPC that returns an entire fixture image
// base64-encoded inside the response message.
//
// v0.1.0 adds three read-only RPCs over the on-disk fragmentation produced
// by the plugin at boot:
//
//	ListImages       — list fragmented images by image_id
//	GetImageMetadata — return the metadata.json for one image as a typed message
//	GetImagePacket   — return one packet, base64-encoded (same wire shape as
//	                   ImageryResult.image_b64)
type OrbitalImagerPluginClient interface {
	RequestImagery(ctx context.Context, in *ImageryRequest, opts ...grpc.CallOption) (*ImageryResult, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResult, error)
	GetImageMetadata(ctx context.Context, in *GetImageMetadataRequest, opts ...grpc.CallOption) (*ImageMetadata, error)
	GetImagePacket(ctx context.Context, in *GetImagePacketRequest, opts ...grpc.CallOption) (*GetImagePacketResult, error)
}

type orbitalImagerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbitalImagerPluginClient(cc grpc.ClientConnInterface) OrbitalImagerPluginClient {
	return &orbitalImagerPluginClient{cc}
}

func (c *orbitalImagerPluginClient) RequestImagery(ctx context.Context, in *ImageryRequest, opts ...grpc.CallOption) (*ImageryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageryResult)
	err := c.cc.Invoke(ctx, OrbitalImagerPlugin_RequestImagery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitalImagerPluginClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResult)
	err := c.cc.Invoke(ctx, OrbitalImagerPlugin_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitalImagerPluginClient) GetImageMetadata(ctx context.Context, in *GetImageMetadataRequest, opts ...grpc.CallOption) (*ImageMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageMetadata)
	err := c.cc.Invoke(ctx, OrbitalImagerPlugin_GetImageMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbitalImagerPluginClient) GetImagePacket(ctx context.Context, in *GetImagePacketRequest, opts ...grpc.CallOption) (*GetImagePacketResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImagePacketResult)
	err := c.cc.Invoke(ctx, OrbitalImagerPlugin_GetImagePacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrbitalImagerPluginServer is the server API for OrbitalImagerPlugin service.
// All implementations must embed UnimplementedOrbitalImagerPluginServer
// for forward compatibility.
//
// OrbitalImagerPlugin is Phare's Orbitport Application Plugin.
//
// v0.0.1 surface: a single unary RPC that returns an entire fixture image
// base64-encoded inside the response message.
//
// v0.1.0 adds three read-only RPCs over the on-disk fragmentation produced
// by the plugin at boot:
//
//	ListImages       — list fragmented images by image_id
//	GetImageMetadata — return the metadata.json for one image as a typed message
//	GetImagePacket   — return one packet, base64-encoded (same wire shape as
//	                   ImageryResult.image_b64)
type OrbitalImagerPluginServer interface {
	RequestImagery(context.Context, *ImageryRequest) (*ImageryResult, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResult, error)
	GetImageMetadata(context.Context, *GetImageMetadataRequest) (*ImageMetadata, error)
	GetImagePacket(context.Context, *GetImagePacketRequest) (*GetImagePacketResult, error)
	mustEmbedUnimplementedOrbitalImagerPluginServer()
}

// UnimplementedOrbitalImagerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbitalImagerPluginServer struct{}

func (UnimplementedOrbitalImagerPluginServer) RequestImagery(context.Context, *ImageryRequest) (*ImageryResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestImagery not implemented")
}
func (UnimplementedOrbitalImagerPluginServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedOrbitalImagerPluginServer) GetImageMetadata(context.Context, *GetImageMetadataRequest) (*ImageMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImageMetadata not implemented")
}
func (UnimplementedOrbitalImagerPluginServer) GetImagePacket(context.Context, *GetImagePacketRequest) (*GetImagePacketResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImagePacket not implemented")
}
func (UnimplementedOrbitalImagerPluginServer) mustEmbedUnimplementedOrbitalImagerPluginServer() {}
func (UnimplementedOrbitalImagerPluginServer) testEmbeddedByValue()                             {}

// UnsafeOrbitalImagerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbitalImagerPluginServer will
// result in compilation errors.
type UnsafeOrbitalImagerPluginServer interface {
	mustEmbedUnimplementedOrbitalImagerPluginServer()
}

func RegisterOrbitalImagerPluginServer(s grpc.ServiceRegistrar, srv OrbitalImagerPluginServer) {
	// If the following call panics, it indicates UnimplementedOrbitalImagerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbitalImagerPlugin_ServiceDesc, srv)
}

func _OrbitalImagerPlugin_RequestImagery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitalImagerPluginServer).RequestImagery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitalImagerPlugin_RequestImagery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitalImagerPluginServer).RequestImagery(ctx, req.(*ImageryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitalImagerPlugin_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitalImagerPluginServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitalImagerPlugin_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitalImagerPluginServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitalImagerPlugin_GetImageMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitalImagerPluginServer).GetImageMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitalImagerPlugin_GetImageMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitalImagerPluginServer).GetImageMetadata(ctx, req.(*GetImageMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbitalImagerPlugin_GetImagePacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImagePacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbitalImagerPluginServer).GetImagePacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbitalImagerPlugin_GetImagePacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbitalImagerPluginServer).GetImagePacket(ctx, req.(*GetImagePacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrbitalImagerPlugin_ServiceDesc is the grpc.ServiceDesc for OrbitalImagerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbitalImagerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbitalimager.OrbitalImagerPlugin",
	HandlerType: (*OrbitalImagerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestImagery",
			Handler:    _OrbitalImagerPlugin_RequestImagery_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _OrbitalImagerPlugin_ListImages_Handler,
		},
		{
			MethodName: "GetImageMetadata",
			Handler:    _OrbitalImagerPlugin_GetImageMetadata_Handler,
		},
		{
			MethodName: "GetImagePacket",
			Handler:    _OrbitalImagerPlugin_GetImagePacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/orbitalimager.proto",
}
