// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/plugins/orbitalimager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Imo           uint64                 `protobuf:"varint,4,opt,name=imo,proto3" json:"imo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageryRequest) Reset() {
	*x = ImageryRequest{}
	mi := &file_proto_plugins_orbitalimager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageryRequest) ProtoMessage() {}

func (x *ImageryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_orbitalimager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageryRequest.ProtoReflect.Descriptor instead.
func (*ImageryRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_orbitalimager_proto_rawDescGZIP(), []int{0}
}

func (x *ImageryRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ImageryRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ImageryRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ImageryRequest) GetImo() uint64 {
	if x != nil {
		return x.Imo
	}
	return 0
}

type ImageryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageB64      string                 `protobuf:"bytes,1,opt,name=image_b64,json=imageB64,proto3" json:"image_b64,omitempty"`        // entire image, base64-encoded
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`        // "image/jpeg" | "image/png"
	CapturedAt    int64                  `protobuf:"varint,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // server-clock Unix seconds
	Sensor        string                 `protobuf:"bytes,4,opt,name=sensor,proto3" json:"sensor,omitempty"`                            // free-form sensor identifier
	ImageHash     []byte                 `protobuf:"bytes,5,opt,name=image_hash,json=imageHash,proto3" json:"image_hash,omitempty"`     // keccak256(decoded bytes)
	Mocked        bool                   `protobuf:"varint,6,opt,name=mocked,proto3" json:"mocked,omitempty"`                           // always true while satellite tasking is fixture-keyed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageryResult) Reset() {
	*x = ImageryResult{}
	mi := &file_proto_plugins_orbitalimager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageryResult) ProtoMessage() {}

func (x *ImageryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_orbitalimager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageryResult.ProtoReflect.Descriptor instead.
func (*ImageryResult) Descriptor() ([]byte, []int) {
	return file_proto_plugins_orbitalimager_proto_rawDescGZIP(), []int{1}
}

func (x *ImageryResult) GetImageB64() string {
	if x != nil {
		return x.ImageB64
	}
	return ""
}

func (x *ImageryResult) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageryResult) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *ImageryResult) GetSensor() string {
	if x != nil {
		return x.Sensor
	}
	return ""
}

func (x *ImageryResult) GetImageHash() []byte {
	if x != nil {
		return x.ImageHash
	}
	return nil
}

func (x *ImageryResult) GetMocked() bool {
	if x != nil {
		return x.Mocked
	}
	return false
}

var File_proto_plugins_orbitalimager_proto protoreflect.FileDescriptor

const file_proto_plugins_orbitalimager_proto_rawDesc = "" +
	"\n" +
	"!proto/plugins/orbitalimager.proto\x12\rorbitalimager\"m\n" +
	"\x0eImageryRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x10\n" +
	"\x03imo\x18\x04 \x01(\x04R\x03imo\"\xb9\x01\n" +
	"\rImageryResult\x12\x1b\n" +
	"\timage_b64\x18\x01 \x01(\tR\bimageB64\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\x03R\n" +
	"capturedAt\x12\x16\n" +
	"\x06sensor\x18\x04 \x01(\tR\x06sensor\x12\x1d\n" +
	"\n" +
	"image_hash\x18\x05 \x01(\fR\timageHash\x12\x16\n" +
	"\x06mocked\x18\x06 \x01(\bR\x06mocked2d\n" +
	"\x13OrbitalImagerPlugin\x12M\n" +
	"\x0eRequestImagery\x12\x1d.orbitalimager.ImageryRequest\x1a\x1c.orbitalimager.ImageryResultB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_plugins_orbitalimager_proto_rawDescOnce sync.Once
	file_proto_plugins_orbitalimager_proto_rawDescData []byte
)

func file_proto_plugins_orbitalimager_proto_rawDescGZIP() []byte {
	file_proto_plugins_orbitalimager_proto_rawDescOnce.Do(func() {
		file_proto_plugins_orbitalimager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugins_orbitalimager_proto_rawDesc), len(file_proto_plugins_orbitalimager_proto_rawDesc)))
	})
	return file_proto_plugins_orbitalimager_proto_rawDescData
}

var file_proto_plugins_orbitalimager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_plugins_orbitalimager_proto_goTypes = []any{
	(*ImageryRequest)(nil), // 0: orbitalimager.ImageryRequest
	(*ImageryResult)(nil),  // 1: orbitalimager.ImageryResult
}
var file_proto_plugins_orbitalimager_proto_depIdxs = []int32{
	0, // 0: orbitalimager.OrbitalImagerPlugin.RequestImagery:input_type -> orbitalimager.ImageryRequest
	1, // 1: orbitalimager.OrbitalImagerPlugin.RequestImagery:output_type -> orbitalimager.ImageryResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_plugins_orbitalimager_proto_init() }
func file_proto_plugins_orbitalimager_proto_init() {
	if File_proto_plugins_orbitalimager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugins_orbitalimager_proto_rawDesc), len(file_proto_plugins_orbitalimager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugins_orbitalimager_proto_goTypes,
		DependencyIndexes: file_proto_plugins_orbitalimager_proto_depIdxs,
		MessageInfos:      file_proto_plugins_orbitalimager_proto_msgTypes,
	}.Build()
	File_proto_plugins_orbitalimager_proto = out.File
	file_proto_plugins_orbitalimager_proto_goTypes = nil
	file_proto_plugins_orbitalimager_proto_depIdxs = nil
}
